version: "2"

services:
  web:
    image: nginx:1.12
    volumes:
      - ./data/website/dist:/usr/share/nginx/html
      - ./data/website/default:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:5000"
    networks:
      - overlay
    depends_on:
      - api

  api:
    image: tomcat:8.0.20-jre8
    ports:
      - "8080:8080"
    networks:
      - overlay
    volumes:
      - ./service/images:/images
      - ./service/varwatch-service-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/varwatch.war
    depends_on:
      - varwatchdb

  beekeeper:
    build: ./beekeeper
    hostname: varwatch
    networks:
      - overlay
    depends_on:
      - varwatchdb
    volumes:
      - /tmp/worker_data:/log/

  varwatchdb:
    image: mysql:5.7.21
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: varwatch
      MYSQL_USER: demo
      MYSQL_PASSWORD: omed
    volumes:
      - ./data/sql/varwatch.sql:/docker-entrypoint-initdb.d/varwatch.sql
      - /tmp/mysql_data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay:

