create table analysis (id bigint generated by default as identity, module_name varchar(255), additional_parameters varchar(255), primary key (id))
create table analysis_job (id bigint generated by default as identity, action varchar(255), additional_parameters varchar(255), last_try timestamp, process varchar(255), retry_count integer, runtime bigint, status varchar(255), submitted timestamp, version bigint not null, analysis_id bigint not null, dataset_id bigint, worker_id bigint, primary key (id))
create table analysis_worker (id bigint generated by default as identity, born timestamp, cause_of_death varchar(255), died timestamp, last_check_in timestamp, status varchar(255), work_done integer, primary key (id))
create table auth_client (id integer generated by default as identity, name varchar(255), real_name varchar(255), redirect varchar(255), secret varchar(255), timestamp timestamp, valid boolean, primary key (id))
create table auth_token (id integer generated by default as identity, expires timestamp, token varchar(255), client_id integer not null, user_id integer not null, primary key (id))
create table auth_user (id integer generated by default as identity, active boolean, address varchar(255), city varchar(255), country varchar(255), email varchar(255), first_name varchar(255), institution varchar(255), last_report timestamp, last_name varchar(255), password varchar(255), phone varchar(255), postal_code varchar(255), pw_source varchar(255), pw_timestamp timestamp, registration_form blob, report_schedule varchar(255), status varchar(255), variant_cont integer, primary key (id))
create table dataset (id bigint generated by default as identity, primary key (id))
create table dataset2hpo (id bigint generated by default as identity, observed boolean, age_of_onset_id bigint, dataset_id bigint not null, phenotype_id bigint not null, primary key (id))
create table dataset_hgmd (alt_base varchar(255), chr_name varchar(255), chr_pos integer, hgmd_acc varchar(255), loftee varchar(255), polyphen double, protein_end integer, protein_start integer, ref_base varchar(255), sift double, id bigint not null, transcript_id integer not null, primary key (id))
create table dataset_status (id bigint generated by default as identity, description varchar(255), status varchar(255), timestamp timestamp, dataset_id bigint not null, user_id integer not null, primary key (id))
create table dataset_vw (completed boolean, date_submitted timestamp, description varchar(255), raw_data blob, raw_data_assembly varchar(255), raw_data_type varchar(255), vcf_file blob, vep_file blob, id bigint not null, age_of_onset_id bigint, client_id integer not null, inheritance_mode_id bigint, user_id integer not null, primary key (id))
create table ensembl_version (id integer generated by default as identity, active boolean, description varchar(255), gen_file blob, name varchar(255), timestamp timestamp, updated boolean, version varchar(255), primary key (id))
create table family (id integer generated by default as identity, description varchar(255), name varchar(255), primary key (id))
create table gene (id integer generated by default as identity, accession_id varchar(255), name varchar(255), omim_gene varchar(255), symbol varchar(255), symbol_source varchar(255), ensembl_id integer not null, primary key (id))
create table gene2family (gene_id integer not null, family_id integer not null, primary key (gene_id, family_id))
create table gene2pathway (gene_id integer not null, pathway_id integer not null, primary key (gene_id, pathway_id))
create table gene_morbid (id integer generated by default as identity, omim_morbid varchar(255), gene_id integer, primary key (id))
create table hpo (id bigint generated by default as identity, description varchar(255), identifier varchar(255), is_obsolete boolean, is_root boolean, subontology varchar(255), primary key (id))
create table hpo_alternative (id bigint generated by default as identity, alternative_identifier varchar(255), term_id bigint, primary key (id))
create table match2variant (id bigint generated by default as identity, acknowledged boolean, timestamp timestamp, variant_id bigint, database_id bigint not null, match_id bigint not null, user_id integer, primary key (id))
create table match_pair (id bigint generated by default as identity, creation_timestamp timestamp, deletion_timestamp timestamp, equal_fam boolean, equal_gene boolean, equal_path boolean, hpo_dist double, identical boolean, match_type varchar(255), notified boolean, database_id bigint not null, primary key (id))
create table pathway (id integer generated by default as identity, description varchar(255), name varchar(255), primary key (id))
create table ref_database (id bigint generated by default as identity, assembly varchar(255), image blob, implementation varchar(255), is_active boolean, timestamp timestamp, name varchar(255), path varchar(255), updated boolean, version varchar(255), primary key (id))
create table transcript (id integer generated by default as identity, bio_type varchar(255), canonical boolean, name varchar(255), protein varchar(255), gene_id integer, primary key (id))
create table variant (id bigint generated by default as identity, alt_Base varchar(255), chr_name varchar(255), chr_pos integer, filter varchar(255), quality integer, ref_base varchar(255), vep_identifier varchar(255), dataset_id bigint not null, primary key (id))
create table variant_effect (id bigint generated by default as identity, cds_end integer, cds_start integer, consequence varchar(255), hgvs_c varchar(255), impact varchar(255), loftee varchar(255), polyphen double, protein_end integer, protein_start integer, sift double, uploaded_variation varchar(255), transcript_id integer not null, variant_id bigint not null, primary key (id))
create table variant_status (id bigint generated by default as identity, status varchar(255), status_value varchar(255), timestamp timestamp, variant_hash varchar(255), variant_raw varchar(255), dataset_id bigint not null, match_variant_id bigint, user_id integer not null, variant_id bigint, primary key (id))
create table varwatch_config (config_key varchar(255) not null, config_value varchar(255), primary key (config_key))
create table varwatch_config_filter (filter_name varchar(255) not null, enabled boolean, filter_type varchar(255), filter_value varchar(255), primary key (filter_name))
alter table analysis_job add constraint FK_37mwr9asebb8wmiha2cr53ugm foreign key (analysis_id) references analysis
alter table analysis_job add constraint FK_m4499xr5qo701obn38suwqru foreign key (dataset_id) references dataset_vw
alter table analysis_job add constraint FK_ixd7j35603xli7hhpw58x4vlt foreign key (worker_id) references analysis_worker
alter table auth_token add constraint FK_f3260vionv7uon0q2p4gchty7 foreign key (client_id) references auth_client
alter table auth_token add constraint FK_aiqc20kpjasth5bxogsragoif foreign key (user_id) references auth_user
alter table dataset2hpo add constraint FK_av7s4av5kjcmlxewrm08cxm52 foreign key (age_of_onset_id) references hpo
alter table dataset2hpo add constraint FK_dbmlohyyrya8kpnoa92tktsxx foreign key (dataset_id) references dataset
alter table dataset2hpo add constraint FK_aadpjxn2xly8ys0l833i6a6fs foreign key (phenotype_id) references hpo
alter table dataset_hgmd add constraint FK_2axo6el7k4msi4l50on6pd2o2 foreign key (transcript_id) references transcript
alter table dataset_hgmd add constraint FK_t7np209ftbyj64yndias8pnrg foreign key (id) references dataset
alter table dataset_status add constraint FK_oa5x9pe2gughi3vb6njymdv1w foreign key (dataset_id) references dataset_vw
alter table dataset_status add constraint FK_sn3d6cx7w7s4q87kexxeobicg foreign key (user_id) references auth_user
alter table dataset_vw add constraint FK_i75ejyth12evbjqgnbxtwum0b foreign key (age_of_onset_id) references hpo
alter table dataset_vw add constraint FK_k528x05aus9nxbo725ldn8vtc foreign key (client_id) references auth_client
alter table dataset_vw add constraint FK_iu7pmstw0m67ovvbx29j1bg6f foreign key (inheritance_mode_id) references hpo
alter table dataset_vw add constraint FK_jn8bs1aqb7gfwen4gisnqamf6 foreign key (user_id) references auth_user
alter table dataset_vw add constraint FK_jgrjbeqna9iwb0ros7rsueer5 foreign key (id) references dataset
alter table gene add constraint FK_dx955rfy1pjr5gc051lx040h0 foreign key (ensembl_id) references ensembl_version
alter table gene2family add constraint FK_7o581vwv8ht74ivfinvn9ma5y foreign key (family_id) references family
alter table gene2family add constraint FK_dc9phlbsk4fxp2hd1lhnw2l0u foreign key (gene_id) references gene
alter table gene2pathway add constraint FK_dsvj4uls5kgp886e2v6bj3neg foreign key (pathway_id) references pathway
alter table gene2pathway add constraint FK_gdl6l6vi5syb6d0ptijtdj0tj foreign key (gene_id) references gene
alter table gene_morbid add constraint FK_tmp7xedkcenengnwdyx52fhir foreign key (gene_id) references gene
alter table hpo_alternative add constraint FK_2pxaogse9j1iehmsha20ddu03 foreign key (term_id) references hpo
alter table match2variant add constraint FK_tnbf3w1frerj8rkg7mxlehmpf foreign key (database_id) references ref_database
alter table match2variant add constraint FK_mvorae0xcmoohykjbvdmg3ipo foreign key (match_id) references match_pair
alter table match2variant add constraint FK_b7eaf3fhw2lkg3ygh5dexilwf foreign key (user_id) references auth_user
alter table match_pair add constraint FK_mt3581mo780s51cpiuqnjlg7j foreign key (database_id) references ref_database
alter table transcript add constraint FK_7d1snswlq2vseapf0owp7innw foreign key (gene_id) references gene
alter table variant add constraint FK_o5jl0e0h8m1jyuria31svantj foreign key (dataset_id) references dataset_vw
alter table variant_effect add constraint FK_3il0p9u5cwc2uta4r6738s5ur foreign key (transcript_id) references transcript
alter table variant_effect add constraint FK_rgbd3nf3p15esg7j9ncanjjc1 foreign key (variant_id) references variant
alter table variant_status add constraint FK_auufbcx1jnh7ycorwiu72r6xb foreign key (dataset_id) references dataset_vw
alter table variant_status add constraint FK_2m2akqgnw86vbfxelinv8693k foreign key (match_variant_id) references match2variant
alter table variant_status add constraint FK_2rg63mc250g0fo66oqhgph77g foreign key (user_id) references auth_user
alter table variant_status add constraint FK_qryg6hb62o0v9nlx7wjhp5vxy foreign key (variant_id) references variant
